version: '2'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS="a.st1.ntp.br,b.st1.ntp.br,c.st1.ntp.br,a.ntp.br,b.ntp.br,c.ntp.br"
